name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    # everyday at 3 am
  schedule:
    - cron:  '0 3 * * *'

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./assets/js/ 

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      working-directory: ${{env.working-directory}}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate json file
      id: generate_json
      working-directory: ${{env.working-directory}}
      run: python generate_blogs.py
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
