name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    # everyday at 3 am
  schedule:
    - cron:  '0 3 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate json file
      id: generate_json
      run: python assets/js/generate_blog.py
